server:
  port: 8085

  servlet:
    context-path: /api

spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML
    encoding: utf-8
    prefix: classpath:/templates/
  application:
    name: jbj
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jbj?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT
    username: root
    password: root
  redis:
    database: 1
    host: localhost
    port: 6379
    #    password: th996105
    timeout: 5000ms
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 20
        min-idle: 0

mybatis-plus:
  configuration:
    ### 开启打印sql配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期 设为一天 (必定过期) 单位: 秒
  timeout: 86400
  # token临时有效期 (指定时间无操作就过期) 单位: 秒
  activity-timeout: 86400
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # 是否尝试从请求体里读取token
  is-read-body: false
  # 是否尝试从header里读取token
  is-read-head: true
  # 是否尝试从cookie里读取token
  is-read-cookie: false
  # token前缀
  token-prefix: "Bearer"
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
#    password: 123456
    # 连接超时时间
    timeout: 10s

default:
  password: "Jbj@123456"

uploadFile:
  domain: https://love.mhwsxr.asia
  #请求 url 中的资源映射
  resourceHandler: /uploadFiles/**
  #自定义上传文件本地保存路径
  location: C:\mhw\uploadFiles

host: https://love.mhwsxr.asia